api:
  image: "lancelotmarti/statbot-api"
  tag: "latest"
  env:
    MODEL_NAME: "default_model"
    MODEL_PATH: "model_path" # IF LOCAL: /root/.cache/huggingface/
    INFERENCE_SERVER_URL: "http://inference-server"
    DB_HOST: "db-host"
    DB_PORT: "5432"
    DB_SCHEMA: "public"
    DB_USERNAME: "user"
    DB_PASS: "password"
    DB_DATABASE: "statbot-db"

ui:
  image: "lancelotmarti/statbot-ui"
  tag: "latest"
  env:
    ADMIN_MAIL: "admin@example.com"

service:
  type: NodePort
  apiPort: 5000

ingress:
    enabled: true
    hostname:  "statbot.lab.sspcloud.fr"