apiVersion: v1
kind: Secret
metadata:
  name: postgresql-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.env.DB_USERNAME | b64enc }}
  # Replace with a secure default or use helm CLI flags to override
  password: {{ .Values.env.DB_PASS | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  access-key: {{ .Values.s3.accessKeyId | b64enc }}
  secret-key: {{ .Values.s3.secretAccessKey | b64enc }}