postgresql:
  clusterName: postgresql-cnpg-postgres
  instances: 1
  storageSize: 20Gi

database:
  image:
    repository: dsccadminch/statbot-db
    tag: "1.0.0"

s3:
  enabled: true # Set to true to use S3
  s3ModelPath: ""
  accessKeyId: ""
  endpoint: ""
  defaultRegion: ""
  secretAccessKey: ""
  sessionToken: ""

env:
  DB_HOST: ""
  DB_PORT: ""
  DB_SCHEMA: ""
  DB_USERNAME: ""
  DB_PASS: ""
  DB_DATABASE: ""