apiVersion: apps/v1
kind: Deployment
metadata:
  name: statbot-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statbot-api
  template:
    metadata:
      labels:
        app: statbot-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image }}:{{ .Values.api.tag }}"
          envFrom:
            - configMapRef:
                name: api-config
            - secretRef:
                name: api-secrets
          volumeMounts:
            - name: userdata
              mountPath: /app/userdata
      volumes:
        - name: userdata
          persistentVolumeClaim:
            claimName: api-pvc
