apiVersion: v1
kind: Service
metadata:
  name: statbot-api
spec:
  selector:
    app: statbot-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.apiPort }}
      targetPort: 5000
  type: ClusterIP
