apiVersion: v1
kind: Service
metadata:
  name: statbot-ui
spec:
  selector:
    app: statbot-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.uiPort }}
      targetPort: 80
  type: {{ .Values.service.type }}
