FROM node:16-alpine as buildstep

WORKDIR /app

COPY src src

COPY public public
COPY package.json .

RUN npm install
ARG REACT_APP_ADMIN_MAIL
ENV REACT_APP_ADMIN_MAIL $REACT_APP_ADMIN_MAIL
RUN npm run build


FROM nginx:stable-alpine

COPY --from=buildstep /app/build /usr/share/nginx/html
COPY nginx.default.conf /etc/nginx/conf.d/default.conf
