FROM python:3.11

WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt

RUN mkdir userdata
ADD data data
COPY *.py .

COPY run.sh .
RUN chmod +x run.sh

RUN pip install gunicorn

CMD ["./run.sh"]